baseURL = 'https://buppy.org'
locale = 'en-us'
title = 'The Brittany Puppy Project'

theme = 'gallery'

copyright = "Made with ❤️  for all the 🐕."
defaultContentLanguage = "en"
disableKinds = ["taxonomy"]
enableRobotsTXT = true
languageCode = "en"
timeZone = "Europe/Berlin"
timeout = "120s"

[params]
defaultTheme = "dark"
description = "All the dogs. All the years. All the destroyed toys, clothing, and furniture."
[params.author]
email = "contact@buppy.org"
name = "Baron and Stacy"
[params.sass]
transpiler = 'dartsass'
[params.socialIcons]
# facebook = "https://www.facebook.com/"
# instagram = "https://www.instagram.com/"
# github = "https://github.com/nicokaiser/hugo-theme-gallery/"
# youtube = "https://www.youtube.com/"
# email = "mailto:user@example.com"
#mastodon = "https://example.com"
#pixelfed = "https://example.com"
#mixcloud = "https://example.com"
#flickr = "https://www.flickr.com"
#500px = "https://500px"
#whatsapp = "1234567890"
[params.gallery]
#boxSpacing = 10
#targetRowHeight = 288
#targetRowHeightTolerance = 0.25

[outputs]
home = ["HTML", "RSS"]
page = ["HTML"]
section = ["HTML"]

[imaging]
quality = 75
resampleFilter = "CatmullRom"
[imaging.exif]
disableDate = false
disableLatLong = true
includeFields = "ImageDescription|Orientation"


[services]
[services.rss]
limit = 100
